### ISSUE TITLE
Wrong code to import

### ISSUE THREAD

**Issue by mi875** [wwwdata/implicitly_animated_reorderable_list#1]
There is the wrong code to import in the "Transition" section of "README.md".

 The wrong code
import 'package:implicitly_animated_reorderable_list/transitions.dart';

The correct code
import 'package:animated_list_plus/transitions.dart';

**Comment by wwwdata** [comment]
yes, I just quickly set this up in a rush. I am going to clean up stuff in the Future. Do you want to help out and open a quick PR that fixes this?

**Comment by mi875** [comment]
Sorry, I cannot do that.
