### ISSUE TITLE
Deploy to pub

### ISSUE THREAD

**Issue by JulianBissekkou** [wwwdata/implicitly_animated_reorderable_list#10]
Hey Ben 👋🏽 ,

I think this maintained version of the animated list is not available on pub? How about releasing it to pub?
We can also integrate the package using git, but an official package would be nice.

Have a nice day 👍🏽

**Comment by wwwdata** [comment]
Hi,
It is already on pub. Just didn't rename the repo name yet on GitHub but the correct name is already in the Readme 

https://pub.dev/packages/animated_list_plus

**Comment by JulianBissekkou** [comment]
Thanks for the information!
