### ISSUE TITLE
Compatibility problem with flutter 3.7 (latest stable)

### ISSUE THREAD

**Issue by pbouttier** [wwwdata/implicitly_animated_reorderable_list#13]
The error : 

```
../../../AppData/Local/Pub/Cache/hosted/pub.dev/animated_list_plus-0.4.4/lib/src/implicitly_animated_reorderable_list.dart:7:1: Error: 'AnimatedItemBuilder' is imported from both 'package:animated_list_plus/src/implicitly_animated_list_base.dart' and 'package:flutter/src/widgets/animated_scroll_view.dart'.

```

There would just need to be prefix the import ? 

Not seen in flutter 3.3.9 and 3.3.10

**Comment by wwwdata** [comment]
yes, Flutter introduced a class with the same name now... Goin to fix it and make a release

**Comment by wwwdata** [comment]
Hiding an import luckily is not breaking backward compatibility, it's just a compiler warning :D so that's what I am going to do now. the least amount of changes and no ugly prefixes everywhere.

**Comment by pbouttier** [comment]
a big thank you :)
