### ISSUE TITLE
If the list is already scrolled, `SizeFadeTransition` animation over shoots

### ISSUE THREAD

**Issue by aytunch** [wwwdata/implicitly_animated_reorderable_list#31]
I tried everything but in a horizontal list, if the list is already scrolled a little amount, the animation overshoots from the left edge of the screen.
Do you have any idea @wwwdata ?

I think the scroll position should be limited to the first remaining item after the update.

https://github.com/wwwdata/implicitly_animated_reorderable_list/assets/6442915/9ee22772-0659-4c4d-a5e2-5bb7a1cc2fa6

**Comment by wwwdata** [comment]
Without a code example. No. Most likely you have an error in your animation where it abruptly shrinks/grows at the end.
