### ISSUE TITLE
Doesn't work with firestore stream

### ISSUE THREAD

**Issue by Clashkid155** [wwwdata/implicitly_animated_reorderable_list#6]
I'm using this with a firestore stream of list. When the database is changed, firestore sends a new list, which is then added to the existing list. Even if firestore sends an entirely new list, I expected the package to at least animate their entries.

I've tried with a stream builder, then also tried with StateNotifier.
**Home Page**
```dart
class NewHome extends ConsumerWidget {
  const NewHome({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final pref = ref.watch(prefProvider);
    final checkBoxState = ref.watch(mainCheckBoxProvider);
    final newSt = ref.watch(fireHomeProvider);
    print("Ses La Rebuild");
    return newSt.when(
        data: (data) {
          final sti = data.docs;
          return ImplicitlyAnimatedList<QueryDocumentSnapshot<User>>(
              items: sti,
              itemBuilder: (context, animation, users, index) {
                final user = users.elementAt(index).data();
                final constructUser = user.copyToUser();
                final imageLink = appendUrl(pref,
                    pack: user.name,
                    currentUrl: user.tray);
                return UserTile(
                  key: ObjectKey(index)
                  image: imageLink
                  isChecked: checkBoxState,
                  time: user.lastUpdated.toDate(),
                  name: user.name),
                  edit: () {
                    print("OK");
                  },
                );
              },
              areItemsTheSame: (a, b) {
                return a.id == b.id;
              });
        },
        error: (error, e) {
          return Text("$error");
        },
        loading: () => const Center(child: CircularProgressIndicator()));
    
  }
}
```
**StateNotifier**
```dart
class HomeStreamNotifier
    extends StateNotifier<List<QueryDocumentSnapshot<User>>> {
  HomeStreamNotifier() : super([]);

  void addUser(var data) {
    state = [...state, ...data];
  }

  void deleteAll() {
    for (var element in state) {
      element.reference.delete();
    }
  }
}
```

**Providers (RiverPod)**
```dart
final fireHomeProvider = StreamProvider<QuerySnapshot<User>>((
  ref,
) async* {
  final userId = ref.watch(prefProvider).getString("userId");
  yield* FirebaseFirestore.instance
      .collection("users")
      .doc(userId)
      .collection("all")
      .snapshots();
});
final prefProvider = Provider<SharedPreferences>((_) => Preferences().pref);

final homeListProvider = StateNotifierProvider<HomeStreamNotifier,
    List<QueryDocumentSnapshot<User>>>((ref) {
  final provider = HomeStreamNotifier();
  ref.listen(fireHomeProvider,
      (previous, AsyncValue<QuerySnapshot<User>> next) {
    provider.addUsers(next.value?.docs);
  });
  return provider;
});
```
This isn't all the code as you would expect since it only features the stream builder implementation.

**Comment by wwwdata** [comment]
So what is happening in your case? The list for example has 1-2 new items but instead of being animated, it just re-renders again without an animation? If that happens then maybe the problem is that Flutter is re-creating the whole widget and cannot track that there only was a change in the Widget-Tree. You are not transitioning into the `loading` state and back into the `data` state which would essentially kill off the widget tree, or?

**Comment by Clashkid155** [comment]
I seem to have made a silly and dumb mistake, I didn't wrap the `UserTile` in any animation. I  do have unnecessary widget rebuilds on that page (home) funny enough, the only widget on that page is what's in my first snippet even though I'm using a `Stateless Widget` and that's why I've `print("Ses La Rebuild");` in my code, but I don't think the library has a hand in the issue.

I still have a problem though, when i remove the item from the list, it shows `Invalid value: Not in inclusive range`.
I think i will leave this open for awhile.
