### ISSUE TITLE
Grid view support

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [wwwdata/implicitly_animated_reorderable_list#7]
I really love the concept of your package,

but I was searching for grid view support for the same thing your list view does

do you think its possible?

if yes can you implement it or give me hints about how to implement it so I add it in pull request

thank you for the awesome package

**Comment by zezo357** [comment]
for my use case I only need the animation part when the grid changes (don't need the reorder functionality ) but I cant find any package that does it

**Comment by zezo357** [comment]
> Did you manage to find something that satisfied your needs or did you create a solution yourself?

Yes, 
https://pub.dev/packages/flutter_reorderable_grid_view

Animates gridview changes, and allows drag and drop
